const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { randomUUID } = require('node:crypto');

const PORT = Number(process.env.PORT || 4173);
const applications = new Map();
const jobs = new Map();
const slots = new Map([
  ['learner-andheri-tue-10', { id: 'learner-andheri-tue-10', kind: 'learner', label: 'Tuesday, 10:00 AM · RTO Andheri', capacity: 20, booked: 18 }],
  ['learner-andheri-wed-11', { id: 'learner-andheri-wed-11', kind: 'learner', label: 'Wednesday, 11:00 AM · RTO Andheri', capacity: 20, booked: 11 }],
  ['practical-andheri-thu-10', { id: 'practical-andheri-thu-10', kind: 'practical', label: 'Thursday, 10:00 AM · RTO Andheri', capacity: 12, booked: 8 }],
  ['practical-andheri-fri-14', { id: 'practical-andheri-fri-14', kind: 'practical', label: 'Friday, 2:00 PM · RTO Andheri', capacity: 12, booked: 12 }],
]);

const newTransitions = {
  submitted: ['documents_pending'], documents_pending: ['documents_verified'], documents_verified: ['learner_test_scheduled'], learner_test_scheduled: ['learner_test_passed'], learner_test_passed: ['learner_license_issued'], learner_license_issued: ['practical_test_scheduled'], practical_test_scheduled: ['practical_test_passed'], practical_test_passed: ['license_issued'], license_issued: [],
};
const renewalTransitions = {
  renewal_started: ['eligibility_checked'], eligibility_checked: ['documents_reverified'], documents_reverified: ['payment_initiated'], payment_initiated: ['payment_pending'], payment_pending: ['payment_confirmed', 'payment_failed'], payment_confirmed: ['license_renewed'], payment_failed: [], license_renewed: [],
};

function json(res, status, data) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(data)); }
function body(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', c => { raw += c; if (raw.length > 100000) req.destroy(); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Invalid JSON request body')); } }); }); }
function title(type) { return type === 'new' ? 'New driving licence' : 'Driving licence renewal'; }
function log(app, from, to, reason, actor = 'system') { app.audit.push({ timestamp: new Date().toISOString(), from, to, reason, actor }); }
function transition(app, to, reason, actor = 'system') { const table = app.type === 'new' ? newTransitions : renewalTransitions; if (!table[app.state]?.includes(to)) throw new Error(`Invalid transition: ${app.state} → ${to}`); const from = app.state; app.state = to; log(app, from, to, reason, actor); }
function queue(app, run, description, delay = 950) { const id = randomUUID(); jobs.set(id, { id, applicationId: app.id, status: 'processing', description }); setTimeout(() => { try { run(); jobs.set(id, { ...jobs.get(id), status: 'complete' }); } catch (error) { jobs.set(id, { ...jobs.get(id), status: 'failed', error: error.message }); } }, delay); return id; }
function processing(app) { return [...jobs.values()].some(j => j.applicationId === app.id && j.status === 'processing'); }
function deadline(app) { if (!app.issuance?.physical?.deadline) return null; return app.issuance.physical.deadline; }
function status(app) { return { applicationId: app.id, type: title(app.type), state: app.state, processing: processing(app), updatedAt: app.audit.at(-1).timestamp, queue: app.queue, issuance: app.issuance ? { digital: { status: app.issuance.digital.status, reference: app.issuance.digital.reference }, physical: app.issuance.physical.status, deadline: deadline(app), eta: app.issuance.physical.eta } : null, payment: app.payment ? { state: app.payment.state, idempotencyKey: app.payment.idempotencyKey } : null }; }
function find(id, res) { const app = applications.get(id); if (!app) { json(res, 404, { error: 'Application not found. Use an ID created in this demo.' }); return null; } return app; }
function issueLicence(app) { transition(app, 'license_issued', 'Mock driving licence issuance'); const dispatchDate = new Date(); const end = new Date(dispatchDate); end.setDate(end.getDate() + 5); app.issuance = { digital: { status: 'available_now', reference: `DIGI-${app.id}`, mocked: true }, physical: { status: 'address_confirmation_pending', deadline: end.toISOString(), eta: null, address: app.address } }; log(app, 'license_issued', 'digilocker_issued', 'Mock digital licence issued independently'); log(app, 'license_issued', 'address_confirmation_pending', 'Physical card awaits address confirmation independently'); }
function completeDocs(app, method) { const verified = method === 'digilocker' ? 'digilocker_verified' : 'in_person_verified'; log(app, method === 'digilocker' ? 'digilocker_fetch_requested' : 'in_person_visit_scheduled', verified, 'Mock document set verified', method === 'digilocker' ? 'mock_digilocker_worker' : 'mock_rto_officer'); transition(app, app.type === 'new' ? 'documents_verified' : 'documents_reverified', 'Canonical documents verified after chosen path', 'system'); }
function create(type, highLoad, identityMethod) { const app = { id: `DL-${Math.floor(100000 + Math.random() * 899999)}`, type, state: type === 'new' ? 'submitted' : 'renewal_started', audit: [], queue: highLoad ? { position: 7, estimatedMinutes: 18 } : null, identityMethod: identityMethod || 'mobile_otp', verification: { method: null, state: null }, expiryDate: '2026-09-05', pendingViolations: false, address: '42 Demo Lane, Andheri East, Mumbai 400093', reservations: [], issuance: null, payment: null };
  log(app, null, app.state, 'Application created with synthetic demo data', 'citizen'); applications.set(app.id, app);
  const next = type === 'new' ? 'documents_pending' : 'eligibility_checked'; const jobId = queue(app, () => transition(app, next, type === 'new' ? 'Mock application intake job' : 'Mock eligibility check: expiry and violation flags reviewed'), 'Initial background processing', 650); return { app, jobId }; }
function serveStatic(req, res) { const pathname = req.url === '/' ? '/index.html' : req.url.split('?')[0]; const safe = path.normalize(pathname).replace(/^([/\\])+/, ''); const file = path.join(__dirname, safe); if (!file.startsWith(__dirname)) return json(res, 403, { error: 'Forbidden' }); const types = { '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'application/javascript; charset=utf-8', '.md': 'text/markdown; charset=utf-8' }; fs.readFile(file, (error, data) => { if (error) return json(res, 404, { error: 'Not found' }); res.writeHead(200, { 'Content-Type': types[path.extname(file)] || 'application/octet-stream', 'Cache-Control': 'no-cache' }); res.end(data); }); }

http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, `http://${req.headers.host}`); const { pathname } = url;
    if (req.method === 'GET' && pathname === '/api/roles/citizen') return json(res, 200, { role: 'Citizen', actions: ['Apply for a new licence', 'Renew driving licence', 'Check application status'] });
    if (req.method === 'GET' && pathname === '/api/roles/manufacturer') return json(res, 200, { role: 'Manufacturer', message: 'Bulk vehicle registration tools are planned for this prototype.' });
    if (req.method === 'GET' && pathname === '/api/roles/commercial') return json(res, 200, { role: 'Commercial Applicant', message: 'Fleet and permit services are planned for this prototype.' });
    if (req.method === 'GET' && pathname === '/api/slots') return json(res, 200, { slots: [...slots.values()].map(s => ({ ...s, remaining: s.capacity - s.booked })) });
    if (req.method === 'POST' && pathname === '/api/applications') { const input = await body(req); if (!['new', 'renewal'].includes(input.type)) return json(res, 400, { error: 'Application type must be new or renewal.' }); if (!['email', 'mobile_otp'].includes(input.identityMethod)) return json(res, 400, { error: 'Choose a mock email or mobile OTP identity path.' }); const made = create(input.type, Boolean(input.highLoad), input.identityMethod); return json(res, 201, { application: status(made.app), jobId: made.jobId, mockNotice: 'Identity, OTP and eligibility data are synthetic for this demo.' }); }
    const statusMatch = pathname.match(/^\/api\/applications\/([^/]+)\/status$/); if (req.method === 'GET' && statusMatch) { const app = find(decodeURIComponent(statusMatch[1]), res); if (app) json(res, 200, status(app)); return; }
    const detailsMatch = pathname.match(/^\/api\/applications\/([^/]+)$/); if (req.method === 'GET' && detailsMatch) { const app = find(decodeURIComponent(detailsMatch[1]), res); if (app) json(res, 200, { ...status(app), audit: app.audit, identityMethod: app.identityMethod, verification: app.verification, expiryDate: app.expiryDate, pendingViolations: app.pendingViolations, address: app.address, reservations: app.reservations }); return; }
    const actionMatch = pathname.match(/^\/api\/applications\/([^/]+)\/actions\/([^/]+)$/);
    if (req.method === 'POST' && actionMatch) {
      const app = find(decodeURIComponent(actionMatch[1]), res); if (!app) return; const action = actionMatch[2]; const input = await body(req); let jobId; let message;
      if (action === 'start-digilocker') { if (!['documents_pending', 'eligibility_checked'].includes(app.state)) return json(res, 409, { error: `Documents cannot be fetched while the application is ${app.state}.` }); app.verification = { method: 'digilocker', state: 'digilocker_fetch_requested' }; log(app, app.state, 'digilocker_fetch_requested', 'Mock DigiLocker document fetch requested', 'citizen'); jobId = queue(app, () => completeDocs(app, 'digilocker'), 'Mock DigiLocker verification'); message = 'Mock DigiLocker document fetch queued.'; }
      else if (action === 'schedule-in-person') { if (!['documents_pending', 'eligibility_checked'].includes(app.state)) return json(res, 409, { error: `An RTO visit cannot be scheduled while the application is ${app.state}.` }); app.verification = { method: 'in_person', state: 'in_person_visit_scheduled' }; log(app, app.state, 'in_person_visit_scheduled', 'Mock RTO document visit scheduled', 'citizen'); message = 'Mock RTO visit scheduled. Use the officer action to complete this demo path.'; }
      else if (action === 'officer-verify') { if (app.verification.state !== 'in_person_visit_scheduled') return json(res, 409, { error: 'An in-person visit must be scheduled before officer verification.' }); jobId = queue(app, () => completeDocs(app, 'in_person'), 'Mock RTO officer verification'); message = 'Mock RTO officer verification queued.'; }
      else if (action === 'record-test-result') { const next = app.state === 'learner_test_scheduled' ? 'learner_test_passed' : app.state === 'practical_test_scheduled' ? 'practical_test_passed' : null; if (!next) return json(res, 409, { error: `A test result cannot be entered while the application is ${app.state}.` }); jobId = queue(app, () => { transition(app, next, 'Mock test result entry'); if (next === 'learner_test_passed') queue(app, () => transition(app, 'learner_license_issued', 'Mock learner licence issuance'), 'Learner licence issuance', 700); else queue(app, () => issueLicence(app), 'Driving licence issuance', 700); }, 'Mock test result processing'); message = 'Mock test result processing queued.'; }
      else if (action === 'initiate-payment') { const key = input.idempotencyKey; if (!key) return json(res, 400, { error: 'An idempotency key is required for mock payment.' }); if (app.payment?.idempotencyKey === key) return json(res, 200, { message: 'Existing payment state returned; no duplicate charge created.', idempotent: true, status: status(app) }); if (app.state !== 'documents_reverified') return json(res, 409, { error: `Payment cannot start while the application is ${app.state}.` }); app.payment = { idempotencyKey: key, state: 'payment_initiated', simulateFailure: Boolean(input.simulateFailure) }; transition(app, 'payment_initiated', 'Mock payment intent created', 'citizen'); jobId = queue(app, () => { transition(app, 'payment_pending', 'Mock gateway awaiting callback'); app.payment.state = 'payment_pending'; }, 'Mock payment gateway initialization', 700); message = 'Payment initiated; awaiting mock bank confirmation.'; }
      else if (action === 'mock-gateway-callback') { if (app.state !== 'payment_pending') return json(res, 409, { error: `A bank callback cannot be handled while the payment is ${app.state}.` }); jobId = queue(app, () => { const next = app.payment.simulateFailure ? 'payment_failed' : 'payment_confirmed'; transition(app, next, app.payment.simulateFailure ? 'Mock gateway callback: payment failed, no amount deducted' : 'Mock gateway callback: payment confirmed', 'mock_gateway_webhook'); app.payment.state = next; if (next === 'payment_confirmed') queue(app, () => transition(app, 'license_renewed', 'Mock renewed licence issuance'), 'Renewed licence issuance', 700); }, 'Mock gateway callback', 900); message = 'Mock bank callback queued; this event, not page navigation, decides the payment result.'; }
      else if (action === 'confirm-address') { if (app.issuance?.physical.status !== 'address_confirmation_pending') return json(res, 409, { error: 'Address confirmation is not available at this stage.' }); app.issuance.physical.address = input.address || app.address; log(app, 'address_confirmation_pending', 'address_confirmed', 'Mock delivery address confirmed', 'citizen'); jobId = queue(app, () => { const date = new Date(); const start = new Date(date); start.setDate(start.getDate() + 7); const end = new Date(date); end.setDate(end.getDate() + 10); app.issuance.physical = { ...app.issuance.physical, status: 'dispatched', eta: `Expected delivery: ${start.toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}–${end.toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}` }; log(app, 'address_confirmed', 'dispatched', 'Mock physical card dispatch created'); }, 'Mock physical dispatch', 700); message = 'Address confirmed; mock dispatch queued.'; }
      else if (action === 'officer-set-address') { if (app.issuance?.physical.status !== 'address_confirmation_pending') return json(res, 409, { error: 'The RTO address fallback is not required now.' }); app.issuance.physical.address = app.address; log(app, 'address_confirmation_pending', 'address_confirmed', 'Mock RTO officer set delivery address', 'mock_rto_officer'); jobId = queue(app, () => { app.issuance.physical.status = 'dispatched'; app.issuance.physical.eta = 'Expected delivery: 7–10 business days from mock dispatch date'; log(app, 'address_confirmed', 'dispatched', 'Mock physical card dispatch created'); }, 'Mock dispatch after RTO address confirmation', 700); message = 'Mock RTO address confirmation queued.'; }
      else return json(res, 404, { error: 'Unknown action.' });
      return json(res, 202, { jobId, message, status: status(app), mockNotice: 'This asynchronous dependency is simulated for the demo.' });
    }
    const reservationMatch = pathname.match(/^\/api\/applications\/([^/]+)\/reservations$/);
    if (req.method === 'POST' && reservationMatch) { const app = find(decodeURIComponent(reservationMatch[1]), res); if (!app) return; const input = await body(req); const slot = slots.get(input.slotId); if (!slot) return json(res, 404, { error: 'Slot not found.' }); const expected = slot.kind === 'learner' ? 'documents_verified' : 'learner_license_issued'; if (app.state !== expected) return json(res, 409, { error: `This ${slot.kind} slot cannot be booked while the application is ${app.state}.` }); /* no await between conditional capacity check and write: atomic in this single-process demo; production uses conditional DB update/row lock */ if (slot.booked >= slot.capacity) return json(res, 409, { error: 'That slot is full. Please choose another slot.' }); slot.booked += 1; app.reservations.push({ slotId: slot.id, label: slot.label, bookedAt: new Date().toISOString() }); transition(app, slot.kind === 'learner' ? 'learner_test_scheduled' : 'practical_test_scheduled', `Atomic reservation: ${slot.label}`, 'citizen'); return json(res, 201, { reservation: app.reservations.at(-1), status: status(app), remaining: slot.capacity - slot.booked }); }
    serveStatic(req, res);
  } catch (error) { json(res, 400, { error: error.message || 'Bad request' }); }
}).listen(PORT, () => console.log(`Parivahan prototype running at http://localhost:${PORT}`));
